# Generated by Django 5.0.11 on 2025-05-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('sub_header', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('path', models.CharField(help_text='\n        <p>An internal path, a download link or an external link</p>\n        e.g.\n        <ul>\n          <li>/contact/<li/>\n          <li>/media/2023-01-01-policy.pdf</li>\n          <li>mailto:club@brightonphoenix.org.uk</li>\n        <ul/>\n        ', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='footer.footersection')),
            ],
        ),
    ]
